name: tif285-env
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - ipywidgets
  - emcee
  - corner
  - scikit-learn
  - pytorch

